from flask import (
    flash,
    json,
    session,
    make_response,
    redirect,
    render_template,
    request,
    url_for,
)
from flask_wtf.csrf import CSRFError
from werkzeug.exceptions import HTTPException

from app.authenication.entra import EntraLogin, LoginRequired
from app.main.client_api import search_clients
from app.main.forms import CookiesForm, WhosCallingForm, SearchUser


def _build_backend_date(year: str, month: str, day: str) -> str | None:
    if not all([year, month, day]):
        return None
    return f"{year}-{month.zfill(2)}-{day.zfill(2)}"


def register_routes(app):
    @app.route("/sign-in", methods=["GET"])
    def sign_in():
        """
        Initiate the sign-in flow using the configured Entra/Silas
        authentication provider.

        Returns:
            Response: The response generated by the authentication flow.
        """
        auth = EntraLogin()
        login = auth.login()
        return login

    @app.route("/sign-in-entra", methods=["GET"])
    def sign_in_entra():
        """
        Initiate the Entra-specific sign-in flow.

        Returns:
            Response: The response generated by the Entra authentication flow.
        """
        auth = EntraLogin()
        login = auth.login_entra()
        return login

    @app.route("/auth/entra-callback")
    def entra_callback():
        """
        Handle the callback from Microsoft Entra after authentication.

        The request query parameters are passed to the authentication
        handler to complete the authentication flow.

        Returns:
            Response: The response generated after processing the callback.
        """

        data = {
            "args": request.args.to_dict(),
        }
        auth = EntraLogin()
        access = auth.callback(data)

        # return access

    @app.route("/sign-out")
    def sign_out():
        """
        Sign the current user out of the authentication session.

        The request query parameters are passed to the authentication
        handler to process the logout flow.

        Returns:
            Response: The response generated by the logout flow.
        """

        auth = EntraLogin()
        access = auth.logout()

        return access

    @app.route("/", methods=["GET", "POST"])
    def receive_call():
        form = WhosCallingForm()
        if form.validate_on_submit():
            session["call_context"] = {"whos_calling": form.whos_calling.data}
            return redirect(url_for("search_client"))
        return render_template("main/index.html", form=form)

    @app.route("/search-client", methods=["GET"])
    @LoginRequired.auth_required
    def search_client():
        form = SearchUser(request.args, meta={"csrf": False})
        submitted = (request.args.get("submitted") == "true") or bool(request.args)

        if not submitted:
            return render_template(
                "services/search.html",
                search={},
                form=form,
            )
        if not form.validate():
            return render_template(
                "services/search.html",
                search={"error": True},
                form=form,
            )

        page = request.args.get("page", 1, type=int)

        full_name = (form.full_name.data or "").strip()
        phone = (form.phone.data or "").strip()
        post_code = (form.postcode.data or "").strip()

        day = (form.date_of_birth_day.data or "").strip()
        month = (form.date_of_birth_month.data or "").strip()
        year = (form.date_of_birth_year.data or "").strip()

        date_of_birth = _build_backend_date(year, month, day)

        if not any([full_name, phone, post_code, day, month, year]):
            search = {"error": True}
            return render_template(
                "services/search.html",
                search=search,
                form=form,
            )

        search_payload = {
            "full_name": full_name,
            "phone": phone,
            "postcode": post_code,
            "date_of_birth": date_of_birth,
            "page": page,
            "call_context": session.get("call_context", {}),
        }

        results = search_clients(search_payload)

        if not results["ok"]:
            return render_template(
                "services/search.html",
                search={
                    "error": True,
                    "error_api": True,
                    "error_message": results["error"],
                    "result": [],
                    "pagination": {
                        "page": 1,
                        "per_page": 20,
                        "total_pages": 1,
                        "total_records": 0,
                        "start": 0,
                        "end": 0,
                    },
                },
                form=form,
            )

        return render_template(
            "services/search.html",
            search=results,
            form=form,
        )

    @app.get("/status")
    def status():
        return "OK"

    @app.get("/help")
    def help():
        return render_template("pages/help.html")

    @app.get("/feedback")
    def feedback():
        return render_template("pages/feedback.html")

    @app.get("/updates")
    def updates():
        return render_template("pages/updates.html")

    @app.get("/accessibility")
    def accessibility():
        return render_template("pages/accessibility.html")

    @app.route("/cookies", methods=["GET", "POST"])
    def cookies():
        form = CookiesForm()
        # Default cookies policy to reject all categories of cookie
        cookies_policy = {"functional": "no", "analytics": "no"}

        if form.validate_on_submit():
            # Update cookies policy consent from form data
            cookies_policy["functional"] = form.functional.data
            cookies_policy["analytics"] = form.analytics.data

            # Create flash message confirmation before rendering template
            flash("You’ve set your cookie preferences.", "success")

            # Create the response so we can set the cookie before returning
            response = make_response(render_template("main/cookies.html", form=form))

            # Set cookies policy for one year
            response.set_cookie(
                "cookies_policy",
                json.dumps(cookies_policy),
                max_age=31557600,
                secure=True,
                samesite="Strict",
            )
            return response
        elif request.method == "GET":
            if request.cookies.get("cookies_policy"):
                # Set cookie consent radios to current consent
                cookies_policy = json.loads(request.cookies.get("cookies_policy"))
                form.functional.data = cookies_policy["functional"]
                form.analytics.data = cookies_policy["analytics"]
            else:
                # If consent not previously set, use default "no" policy
                form.functional.data = cookies_policy["functional"]
                form.analytics.data = cookies_policy["analytics"]
        return render_template("main/cookies.html", form=form)

    @app.get("/privacy")
    def privacy():
        return render_template("main/privacy.html")

    @app.errorhandler(HTTPException)
    def http_exception(error):
        return render_template(f"errors/{error.code}.html"), error.code

    @app.errorhandler(CSRFError)
    def csrf_error(error):
        flash("The form you were submitting has expired. Please try again.")
        return redirect(request.full_path)
