# Production Environment Values
# Overrides for the Production environment

replicaCount: 4

image:
  pullPolicy: Always
  containerPort: 3000

ingress:
  enabled: true
  className: "modsec"
  annotations:
    external-dns.alpha.kubernetes.io/set-identifier: laa-cla-operator-app-laa-cla-operator-app-production-green
    external-dns.alpha.kubernetes.io/aws-weight: "100"
  hosts:
    - host: laa-cla-operator-app.cloud-platform.service.justice.gov.uk
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls:
    - secretName: laa-cla-operator-app-production-tls
      hosts:
        - laa-cla-operator-app.cloud-platform.service.justice.gov.uk
  whitelist:
    enabled: true

resources: {}

autoscaling:
  enabled: true
  minReplicas: 3
  maxReplicas: 10
  targetCPUUtilizationPercentage: 70
  targetMemoryUtilizationPercentage: 80

# Environment variables can be added here
envVars:
  BACKEND_BASE_URL:
    # Using service name instead of external domain name
    value: "http://cla-backend-app.laa-cla-backend-production.svc.cluster.local"
  NODE_ENV:
    value: "production"
  ENTRA_REDIRECT_URI:
    value: ""
