name: Feature Branch

run-name: Feature - ${{ github.head_ref || github.ref_name }}

on:
  push:
    branches-ignore:
      - main
  pull_request:
    types:
      - opened
      - reopened
      - synchronize

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref_name }}
  cancel-in-progress: true

permissions: {}

jobs:
  test:
    name: Test
    uses: ./.github/workflows/test.yml
    permissions:
      contents: read

  lint:
    name: Lint
    uses: ./.github/workflows/lint.yml
    permissions:
      contents: read

  #   TODO: Re-enable this when we have tests with coverage reports to analyse
  #   name: Static Analysis
  #   needs: test
  #   uses: ./.github/workflows/static-analysis.yml
  #   secrets:
  #     SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
  #     GITLEAKS_LICENSE: ${{ secrets.GITLEAKS_LICENSE }}

  build-and-push:
    name: Build
    uses: ./.github/workflows/build.yml
    needs: [lint, test]
    permissions:
      contents: read
      id-token: write
    with:
      ECR_REGION: ${{vars.ECR_REGION}}
      ECR_REPOSITORY: ${{vars.ECR_REPOSITORY}}
    secrets:
      ECR_ROLE_TO_ASSUME: ${{ secrets.ECR_ROLE_TO_ASSUME }}

  snyk-image-scan:
    name: Build
    needs: [build-and-push]
    uses: ministryofjustice/laa-reusable-github-actions/.github/workflows/sast.yml@df9a4a8ad625a391c27ccf81a1c1a2d7b23e6474 #unversioned
    permissions:
      id-token: write
      contents: read
      security-events: write
      actions: read
    with:
      image_uri: ${{ needs.build-and-push.outputs.image_tag }}
      exclude_base_image_vulns: true
      dockerfile_path: Dockerfile
    secrets:
      SNYK_CLIENT_ID: ${{ secrets.SNYK_CLIENT_ID }}
      SNYK_CLIENT_SECRET: ${{ secrets.SNYK_CLIENT_SECRET }}
      ECR_ROLE_TO_ASSUME: ${{ secrets.ECR_ROLE_TO_ASSUME }}


  deploy-ephemeral:
     name: Ephemeral
     uses: ./.github/workflows/deploy-ephemeral.yml
     needs: [build-and-push]
     permissions:
       contents: read
       id-token: write
       pull-requests: write
     with:
       environment: uat
       ECR_REGION: ${{vars.ECR_REGION}}
       ECR_REPOSITORY: ${{vars.ECR_REPOSITORY}}
     secrets:
       ECR_REGISTRY_URL: ${{ secrets.ECR_REGISTRY_URL }}
       ECR_ROLE_TO_ASSUME: ${{ secrets.ECR_ROLE_TO_ASSUME }}
       KUBE_CERT: ${{ secrets.KUBE_CERT }}
       KUBE_CLUSTER: ${{ secrets.KUBE_CLUSTER }}
       KUBE_NAMESPACE: ${{ secrets.KUBE_NAMESPACE }}
       KUBE_TOKEN: ${{ secrets.KUBE_TOKEN }}
