name: Test

on: workflow_call

permissions: {}

env:
  SECRET_KEY: "TEST_KEY"

jobs:
  unit_test:
    name: Unit Test & Coverage
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout the repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Set up Node.js
        uses: actions/setup-node@6044e13b5dc448c55e2357c09f80417699197238 # v6.2.0
        with:
          node-version: "24.10.0"

      - name: Enable Corepack
        run: |
          corepack enable

      - name: Install dependencies
        run: |
          yarn install --immutable

      - name: Unit test with coverage check
        run: |
          yarn coverage

      - name: Upload coverage report
        if: ${{ always() }}
        uses: actions/upload-artifact@b7c566a772e6b6bfb58ed0dc250532a479d7789f # v6.0.0
        with:
          name: coverage-report
          path: coverage/

